#!/bin/bash
set -e

# PRZ Health Service — Deploy Script
# Generated by: OPS agent

PROJECT_ID=${1:?"Usage: ./deploy.sh <PROJECT_ID>"}
REGION="northamerica-northeast1"
SERVICE="prz-health-svc"
IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/prz-core-repo/health-svc:latest"

echo ">>> 🚀 Deploying PRZ Health Service"
echo ">>> 🍁 Region: ${REGION} (AIDA-2026)"

gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

docker build --platform linux/amd64 -t ${IMAGE} .
docker push ${IMAGE}

gcloud run deploy ${SERVICE} \
  --image ${IMAGE} \
  --region ${REGION} \
  --platform managed \
  --allow-unauthenticated \
  --set-env-vars NODE_ENV=production,PRZ_COMPLIANCE_MODE=STRICT,LOG_LEVEL=info,REGION=${REGION} \
  --memory 512Mi \
  --cpu 1 \
  --port 8080

URL=$(gcloud run services describe ${SERVICE} --region ${REGION} --format 'value(status.url)')

echo "──────────────────────────────────"
echo "✅ DEPLOYED: ${URL}"
echo "   Health:   ${URL}/health"
echo "   Metrics:  ${URL}/metrics"
echo "──────────────────────────────────"
