/**
 * Circuit Breaker — Protects downstream services
 * Generated by: BUILDER agent
 */

import { CircuitBreakerState } from './types';

export class CircuitBreaker {
  private state: CircuitBreakerState;
  private halfOpenAttempts = 0;
  private readonly maxHalfOpenAttempts: number;

  constructor(
    private readonly failureThreshold: number = 5,
    private readonly resetTimeoutMs: number = 30000,
    maxHalfOpenAttempts: number = 3
  ) {
    this.maxHalfOpenAttempts = maxHalfOpenAttempts;
    this.state = {
      state: 'CLOSED',
      failureCount: 0,
      threshold: failureThreshold,
      resetTimeout: resetTimeoutMs
    };
  }

  get current(): CircuitBreakerState {
    this.checkReset();
    return { ...this.state };
  }

  get isOpen(): boolean {
    this.checkReset();
    return this.state.state === 'OPEN';
  }

  async execute<T>(operation: () => Promise<T>): Promise<T> {
    this.checkReset();

    if (this.state.state === 'OPEN') {
      throw new Error('Circuit breaker is OPEN — request rejected');
    }

    try {
      const result = await operation();
      this.onSuccess();
      return result;
    } catch (error) {
      this.onFailure();
      throw error;
    }
  }

  private onSuccess(): void {
    if (this.state.state === 'HALF_OPEN') {
      this.halfOpenAttempts++;
      if (this.halfOpenAttempts >= this.maxHalfOpenAttempts) {
        this.state.state = 'CLOSED';
        this.state.failureCount = 0;
        this.halfOpenAttempts = 0;
      }
    } else {
      this.state.failureCount = 0;
    }
  }

  private onFailure(): void {
    this.state.failureCount++;
    this.state.lastFailure = new Date().toISOString();

    if (this.state.failureCount >= this.state.threshold) {
      this.state.state = 'OPEN';
    }
  }

  private checkReset(): void {
    if (this.state.state !== 'OPEN' || !this.state.lastFailure) return;

    const elapsed = Date.now() - new Date(this.state.lastFailure).getTime();
    if (elapsed >= this.state.resetTimeout) {
      this.state.state = 'HALF_OPEN';
      this.halfOpenAttempts = 0;
    }
  }

  reset(): void {
    this.state = {
      state: 'CLOSED',
      failureCount: 0,
      threshold: this.failureThreshold,
      resetTimeout: this.resetTimeoutMs
    };
    this.halfOpenAttempts = 0;
  }
}
