/**
 * Priority Lane Queue — Critical messages bypass normal traffic
 * Generated by: BUILDER agent
 */

import { PriorityMessage, QueueStatus } from './types';

const PRIORITY_ORDER: Record<PriorityMessage['priority'], number> = {
  critical: 0,
  high: 1,
  normal: 2,
  low: 3
};

export class PriorityQueue {
  private queue: PriorityMessage[] = [];
  private processing = false;
  private lastProcessed?: string;
  private readonly maxSize: number;

  constructor(maxSize: number = 1000) {
    this.maxSize = maxSize;
  }

  enqueue(message: PriorityMessage): boolean {
    if (this.queue.length >= this.maxSize) {
      // Drop lowest priority message if at capacity
      if (PRIORITY_ORDER[message.priority] < PRIORITY_ORDER[this.queue[this.queue.length - 1].priority]) {
        this.queue.pop();
      } else {
        return false;
      }
    }

    this.queue.push(message);
    this.queue.sort((a, b) => PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority]);
    return true;
  }

  dequeue(): PriorityMessage | undefined {
    const msg = this.queue.shift();
    if (msg) {
      this.lastProcessed = msg.id;
    }
    return msg;
  }

  peek(): PriorityMessage | undefined {
    return this.queue[0];
  }

  get status(): QueueStatus {
    return {
      depth: this.queue.length,
      criticalCount: this.queue.filter(m => m.priority === 'critical').length,
      processing: this.processing,
      lastProcessed: this.lastProcessed
    };
  }

  async processAll(handler: (msg: PriorityMessage) => Promise<void>): Promise<number> {
    this.processing = true;
    let processed = 0;

    while (this.queue.length > 0) {
      const msg = this.dequeue()!;
      await handler(msg);
      processed++;
    }

    this.processing = false;
    return processed;
  }

  clear(): void {
    this.queue = [];
  }
}
