/**
 * PRZ Health Service — HTTP Server
 * Generated by: BUILDER agent
 */

import * as http from 'node:http';
import { randomUUID } from 'node:crypto';
import { CircuitBreaker } from './circuit-breaker';
import { PriorityQueue } from './priority-queue';
import { ServiceConfig, HealthStatus, ApiResponse, PriorityMessage } from './types';

const startTime = Date.now();

const config: ServiceConfig = {
  port: parseInt(process.env.PORT || '8080', 10),
  region: process.env.REGION || 'northamerica-northeast1',
  compliance: process.env.PRZ_COMPLIANCE_MODE || 'STRICT',
  circuitBreaker: {
    failureThreshold: 5,
    resetTimeoutMs: 30000,
    halfOpenMaxAttempts: 3
  },
  logging: {
    level: (process.env.LOG_LEVEL as any) || 'info',
    format: 'json'
  }
};

const circuitBreaker = new CircuitBreaker(
  config.circuitBreaker.failureThreshold,
  config.circuitBreaker.resetTimeoutMs,
  config.circuitBreaker.halfOpenMaxAttempts
);

const priorityQueue = new PriorityQueue(1000);

function log(level: string, msg: string, data?: Record<string, unknown>): void {
  const entry = {
    level: level.toUpperCase(),
    msg,
    timestamp: new Date().toISOString(),
    region: config.region,
    ...data
  };
  console.log(JSON.stringify(entry));
}

function respond<T>(res: http.ServerResponse, statusCode: number, body: ApiResponse<T>, requestId: string): void {
  res.writeHead(statusCode, {
    'Content-Type': 'application/json',
    'X-Request-Id': requestId,
    'X-Region': config.region,
    'X-Compliance': config.compliance
  });
  res.end(JSON.stringify(body));
}

function handleHealth(req: http.IncomingMessage, res: http.ServerResponse, requestId: string): void {
  const circuit = circuitBreaker.current;
  const health: HealthStatus = {
    status: circuit.state === 'CLOSED' ? 'healthy' : circuit.state === 'HALF_OPEN' ? 'degraded' : 'unhealthy',
    timestamp: new Date().toISOString(),
    uptime: Math.floor((Date.now() - startTime) / 1000),
    version: '3.0.0',
    region: config.region,
    compliance: config.compliance
  };

  log('INFO', 'Health Check Passed', { circuit: circuit.state });

  respond(res, 200, {
    success: true,
    data: { ...health, circuit: circuit.state },
    timestamp: health.timestamp,
    requestId
  }, requestId);
}

function handleCircuit(req: http.IncomingMessage, res: http.ServerResponse, requestId: string): void {
  respond(res, 200, {
    success: true,
    data: circuitBreaker.current,
    timestamp: new Date().toISOString(),
    requestId
  }, requestId);
}

async function handleQueuePost(req: http.IncomingMessage, res: http.ServerResponse, requestId: string): Promise<void> {
  const body = await readBody(req);
  try {
    const parsed = JSON.parse(body);
    const message: PriorityMessage = {
      id: randomUUID(),
      priority: parsed.priority || 'normal',
      payload: parsed.payload,
      timestamp: Date.now(),
      source: parsed.source || 'api'
    };

    const accepted = priorityQueue.enqueue(message);
    if (accepted) {
      log('INFO', 'Message enqueued', { messageId: message.id, priority: message.priority });
      respond(res, 201, { success: true, data: { messageId: message.id }, timestamp: new Date().toISOString(), requestId }, requestId);
    } else {
      respond(res, 429, { success: false, error: 'Queue at capacity', timestamp: new Date().toISOString(), requestId }, requestId);
    }
  } catch {
    respond(res, 400, { success: false, error: 'Invalid JSON body', timestamp: new Date().toISOString(), requestId }, requestId);
  }
}

function handleQueueStatus(req: http.IncomingMessage, res: http.ServerResponse, requestId: string): void {
  respond(res, 200, {
    success: true,
    data: priorityQueue.status,
    timestamp: new Date().toISOString(),
    requestId
  }, requestId);
}

function handleMetrics(req: http.IncomingMessage, res: http.ServerResponse, requestId: string): void {
  const uptime = Math.floor((Date.now() - startTime) / 1000);
  const circuit = circuitBreaker.current;
  const queue = priorityQueue.status;

  const metrics = [
    `# HELP prz_uptime_seconds Service uptime in seconds`,
    `# TYPE prz_uptime_seconds gauge`,
    `prz_uptime_seconds ${uptime}`,
    `# HELP prz_circuit_breaker_state Circuit breaker state (0=CLOSED, 1=HALF_OPEN, 2=OPEN)`,
    `# TYPE prz_circuit_breaker_state gauge`,
    `prz_circuit_breaker_state ${circuit.state === 'CLOSED' ? 0 : circuit.state === 'HALF_OPEN' ? 1 : 2}`,
    `# HELP prz_circuit_breaker_failures Total circuit breaker failures`,
    `# TYPE prz_circuit_breaker_failures gauge`,
    `prz_circuit_breaker_failures ${circuit.failureCount}`,
    `# HELP prz_queue_depth Current queue depth`,
    `# TYPE prz_queue_depth gauge`,
    `prz_queue_depth ${queue.depth}`,
    `# HELP prz_queue_critical_count Critical messages in queue`,
    `# TYPE prz_queue_critical_count gauge`,
    `prz_queue_critical_count ${queue.criticalCount}`
  ].join('\n');

  res.writeHead(200, { 'Content-Type': 'text/plain', 'X-Request-Id': requestId });
  res.end(metrics);
}

function readBody(req: http.IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', chunk => data += chunk);
    req.on('end', () => resolve(data));
    req.on('error', reject);
  });
}

const server = http.createServer(async (req, res) => {
  const requestId = randomUUID();
  const url = req.url || '/';
  const method = req.method || 'GET';

  log('DEBUG', `${method} ${url}`, { requestId });

  try {
    if (url === '/health' && method === 'GET') return handleHealth(req, res, requestId);
    if (url === '/circuit' && method === 'GET') return handleCircuit(req, res, requestId);
    if (url === '/queue' && method === 'POST') return await handleQueuePost(req, res, requestId);
    if (url === '/queue/status' && method === 'GET') return handleQueueStatus(req, res, requestId);
    if (url === '/metrics' && method === 'GET') return handleMetrics(req, res, requestId);

    respond(res, 404, { success: false, error: 'Not Found', timestamp: new Date().toISOString(), requestId }, requestId);
  } catch (err: any) {
    log('ERROR', 'Request failed', { requestId, error: err.message });
    respond(res, 500, { success: false, error: 'Internal Server Error', timestamp: new Date().toISOString(), requestId }, requestId);
  }
});

server.listen(config.port, () => {
  log('INFO', `PRZ Health Service v3.0 started`, {
    port: config.port,
    region: config.region,
    compliance: config.compliance,
    circuit: 'CLOSED'
  });
});
