/**
 * PRZ Health Service — Type Definitions
 * Generated by: ARCHITECT agent
 * Task: PRZ Health Service with circuit breaker and AIDA-2026 compliance
 */

export interface HealthStatus {
  status: 'healthy' | 'degraded' | 'unhealthy';
  timestamp: string;
  uptime: number;
  version: string;
  region: string;
  compliance: string;
}

export interface CircuitBreakerState {
  state: 'CLOSED' | 'OPEN' | 'HALF_OPEN';
  failureCount: number;
  lastFailure?: string;
  threshold: number;
  resetTimeout: number;
}

export interface ServiceConfig {
  port: number;
  region: string;
  compliance: string;
  circuitBreaker: {
    failureThreshold: number;
    resetTimeoutMs: number;
    halfOpenMaxAttempts: number;
  };
  logging: {
    level: 'debug' | 'info' | 'warn' | 'error';
    format: 'json' | 'text';
  };
}

export interface PriorityMessage {
  id: string;
  priority: 'critical' | 'high' | 'normal' | 'low';
  payload: unknown;
  timestamp: number;
  source: string;
}

export interface QueueStatus {
  depth: number;
  criticalCount: number;
  processing: boolean;
  lastProcessed?: string;
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  timestamp: string;
  requestId: string;
}
